source "https://rubygems.org"
gem "rails", "3.2.17"

group :development do
  gem "pry"

end

group :development, :test do
  gem "sqlite3"
  gem "sequel"
  gem "mocha"
  gem "minitest"
  gem "factory_girl"
  gem "guard"
  gem "terminal-notifier-guard"
  gem "guard-bundler"
  gem "guard-minitest"
  gem "guard-rails_best_practices"
  gem "reek"
end

